---
# tasks file for jdk install


- name: download oracle java8 tarball
  # Need to use wget instead of get_url, because get_url does not support
  # these options.
  command: "wget --no-cookies --no-check-certificate --header='Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' {{ jdk_url }}"
  args:
    chdir: /tmp
    creates: jdk-{{ jdk_file_version }}-linux-x64.tar.gz

- name: extract java8 tarball
  unarchive:
    copy: no
    src: /tmp/jdk-{{ jdk_file_version }}-linux-x64.tar.gz
    dest: /tmp
    creates: /tmp/jdk{{ jdk_version }}

- name: setup owner of java8 directory
  file:
    path: /tmp/jdk{{ jdk_version }}
    state: directory
    recurse: yes
    owner: root
    group: root

- name: create jdk parent directory
  file: path={{ jdk_parent_directory }} state=directory owner=root group=root mode=0755

- name: install untar jdk jdk directory
  shell: mv /tmp/jdk{{ jdk_version }} {{ jdk_prefix }}
