---
# tasks file for jdk

- name: check if already installed
  stat: path={{ jdk_prefix }}/bin
  register: jdk_bin
  changed_when: jdk_bin.stat.exists == False

- include: install.yml
  when: jdk_bin.stat.exists == False

- name: clean downloaded file
  file: path=/tmp/jdk-{{ jdk_file_version }}-linux-x64.tar.gz state=absent
